import { company, completedProjects, contactHref, projectTypes, serviceAreas } from "../lib/site-data";
import { Arrow, CTA, PageIntro, SiteShell } from "./site";

const brochure = "/downloads/steadwin-group-company-profile.pdf";

export function ProjectQuickActions() {
  return <section className="section project-quick-section"><div className="container project-quick-grid"><div><p className="eyebrow">PLAN WITH CLARITY</p><h2>Start with a quote<br />or a site visit.</h2><p>Share the space, the work you need and the location. We will take the conversation forward from there.</p></div><div className="project-quick-actions"><a className="button button-blue" href={contactHref(undefined, undefined, "Free site visit")}>Book Free Site Visit <Arrow /></a><a className="button button-outline" href={brochure} download>Download Company Profile <Arrow /></a></div></div></section>;
}

export function ProjectsPage() {
  return <SiteShell active="projects"><PageIntro label="PROJECT PLANNING" current="Projects" title={<>Every project starts<br />with a <em>clear scope.</em></>} text="Choose a complete interior, a commercial fit-out or the specialist work your site needs. We discuss the actual requirements before quotation and execution." />
    <section className="section completed-projects" aria-labelledby="completed-work-title"><div className="container"><div className="section-heading completed-project-heading"><div><p className="eyebrow">COMPLETED WORK</p><h2 id="completed-work-title">Spaces brought<br />to life.</h2></div><p>Selected residential interior photographs from completed STEADWIN GROUP work. Design inspiration is shown separately in the Gallery.</p></div><div className="completed-project-grid">{completedProjects.map((project, index) => <article className="completed-project-card" key={project.image}><div className="completed-project-image"><img src={'/assets/' + project.image} alt={project.alt} loading={index < 6 ? "eager" : "lazy"} decoding="async" /></div><div className="completed-project-caption"><div><p>{project.category}</p><h3>{project.title}</h3></div><span aria-hidden="true">{String(index + 1).padStart(2, "0")}</span></div></article>)}</div><p className="completed-project-note">Looking for a style reference? <a href="/gallery/">View our separate design-inspiration gallery <Arrow /></a>.</p></div></section>
    <section className="section project-directory"><div className="container"><div className="section-heading"><div><p className="eyebrow">WORK WE CAN PLAN TOGETHER</p><h2>One site.<br />Every important detail.</h2></div><p>Explore the types of projects and related works we can coordinate for your home or business.</p></div><div className="project-board">{projectTypes.map(item => <article key={item.number}><span className="project-number">{item.number}</span><p className="eyebrow">{item.label}</p><h3>{item.title}</h3><p>{item.text}</p><ul>{item.points.map(point => <li key={point}><span aria-hidden="true">✓</span>{point}</li>)}</ul><a className="text-link" href={contactHref(item.service, item.project, "Project quotation")}>Discuss this scope <Arrow /></a></article>)}</div></div></section>
    <section className="section dark-section"><div className="container site-visit-banner"><div><p className="eyebrow">FREE SITE VISIT</p><h2>Let’s understand<br />your space first.</h2><p>Share your location, approximate area and the work you need. Floor plans, site photos and inspiration images can be discussed on WhatsApp.</p></div><div><a className="button button-light" href={contactHref(undefined, undefined, "Free site visit")}>Book Free Site Visit <Arrow /></a><a className="inline-phone" href={"tel:" + company.tel}>Call {company.phone}</a></div></div></section>
    <section className="section soft-section"><div className="container proof-grid"><div><p className="eyebrow">PLAN YOUR OWN SPACE</p><h2>A portfolio is<br />only the beginning.</h2><p>Every site has its own layout, services, materials and finish details. Share your requirement and we can discuss a suitable scope for your home or business.</p><a className="text-link" href="/gallery/">Open design inspiration <Arrow /></a></div><div className="brochure-card"><span className="brochure-mark">PDF</span><p className="eyebrow">COMPANY PROFILE</p><h3>Keep our services<br />on hand.</h3><p>Download a concise overview of STEADWIN GROUP, our interior scope and contact details.</p><a className="button button-dark" href={brochure} download>Download Profile <Arrow /></a></div></div></section>
    <CTA title="Let’s plan your next project." text="Start with a complete brief or just the service you need. We will help you define the next step." />
  </SiteShell>;
}

export function ContactGrowth() {
  return <>
    <section className="section site-visit-section"><div className="container site-visit-grid"><div><p className="eyebrow">FREE SITE VISIT</p><h2>Start with<br />your actual space.</h2><p>For homes, offices, shops and showrooms, share the location, photos or floor plan through the enquiry form. We will discuss the requirement before finalising the scope.</p><a className="button button-blue" href={contactHref(undefined, undefined, "Free site visit")}>Book Free Site Visit <Arrow /></a></div><div className="visit-checklist"><p className="eyebrow">HELPFUL TO SHARE</p><ul><li><span>01</span>Project location and approximate area</li><li><span>02</span>Residential or commercial requirement</li><li><span>03</span>Photos, plan or reference images</li><li><span>04</span>Preferred work timeline</li></ul></div></div></section>
    <section className="section soft-section service-area-section"><div className="container service-area-grid"><div><p className="eyebrow">BENGALURU SERVICE AREA</p><h2>Interior work<br />near your space.</h2><p>Our office is in JP Nagar. Tell us your location and requirement to discuss site feasibility and the next step.</p><a className="text-link" href={"https://www.google.com/maps/search/?api=1&query=" + encodeURIComponent(company.address)} target="_blank" rel="noopener noreferrer">View office location <Arrow /></a></div><div className="area-list">{serviceAreas.map(area => <span key={area}>{area}</span>)}</div></div></section>
    <section className="section feedback-section"><div className="container feedback-grid"><div><p className="eyebrow">CLIENT FEEDBACK</p><h2>Your experience<br />matters to us.</h2></div><div><p>We publish feedback only with client permission. If STEADWIN GROUP has worked on your space, share your feedback directly with our team.</p><a className="button button-dark" href="https://wa.me/918792695400?text=Hello%20STEADWIN%20GROUP%2C%20I%20would%20like%20to%20share%20my%20project%20feedback." target="_blank" rel="noopener noreferrer">Share Feedback <Arrow /></a></div></div></section>
    <section className="section brochure-section"><div className="container brochure-strip"><div><p className="eyebrow">COMPANY PROFILE</p><h2>Everything we do,<br />in one download.</h2></div><a className="button button-outline" href={brochure} download>Download Company Profile <Arrow /></a></div></section>
  </>;
}
