import { Arrow, Breadcrumbs, CTA, ImagePanel, PageIntro, Process, ServiceCards, SiteShell } from "./site";
import { ContactGrowth, ProjectQuickActions } from "./growth";
import { company, contactHref, designConcepts, services } from "../lib/site-data";

const homeSlides = [
  {
    image: "design-concepts/01-1000000778.webp",
    alt: "Interior concept with living space, work corner and warm wood details",
    eyebrow: "DESIGN + EXECUTION FOR EVERY SPACE",
    title: "Designed for life.",
    accent: "Built to work.",
    copy: "From the first layout to the final handover, STEADWIN GROUP brings design, interiors and execution together under one coordinated team.",
  },
  {
    image: "design-concepts/02-1000003692.webp",
    alt: "Modern kitchen and dining concept",
    eyebrow: "RESIDENTIAL INTERIORS",
    title: "A better home,",
    accent: "in every detail.",
    copy: "Kitchens, wardrobes, living spaces, finishes and services planned around the way your family lives every day.",
  },
  {
    image: "design-concepts/09-1000003708.webp",
    alt: "Contemporary kitchen execution concept",
    eyebrow: "BUILDERS + COMMERCIAL SPACES",
    title: "One brief.",
    accent: "One execution team.",
    copy: "For builders, offices, shops and showrooms: interiors, partitions, electrical, plumbing, glass and finishing work in one clear scope.",
  },
];

export function HomePage() {
  return <SiteShell active="home">
    <section className="steadwin-hero" aria-label="STEADWIN GROUP design and execution">
      <div className="steadwin-hero-slides" data-hero-slider>
        {homeSlides.map((slide, index) => <article className={"steadwin-hero-slide" + (index === 0 ? " is-active" : "")} data-hero-slide={index} key={slide.image} aria-hidden={index === 0 ? undefined : true}>
          <img src={"/assets/" + slide.image} width="1600" height="1200" alt={slide.alt} fetchPriority={index === 0 ? "high" : undefined} loading={index === 0 ? "eager" : "lazy"} />
          <span className="steadwin-hero-shade" aria-hidden="true"></span>
          <div className="container steadwin-hero-content"><p className="eyebrow">{slide.eyebrow}<span className="hero-rule"></span></p>{index === 0 ? <h1 className="hero-slide-title">{slide.title}<br /><span>{slide.accent}</span></h1> : <p className="hero-slide-title">{slide.title}<br /><span>{slide.accent}</span></p>}<p>{slide.copy}</p><div className="hero-actions"><a className="button button-blue" href={contactHref(undefined, undefined, "Free quotation")}>Get free quotation <Arrow /></a><a className="button button-outline" href="https://wa.me/918792695400" target="_blank" rel="noopener noreferrer"><span className="whatsapp-dot">●</span> WhatsApp us</a></div></div>
        </article>)}
      </div>
      <div className="container hero-slider-controls" aria-label="Home slides">{homeSlides.map((slide, index) => <button className={index === 0 ? "is-active" : undefined} type="button" data-hero-dot={index} key={slide.image} aria-label={"Show slide " + (index + 1)} aria-current={index === 0 ? "true" : undefined}><span>{String(index + 1).padStart(2, "0")}</span><i></i></button>)}</div>
    </section>
    <div className="feature-strip"><div className="container feature-grid"><div><span className="feature-icon">✦</span><span><strong>Design + execution</strong><small>One clear project journey.</small></span></div><div><span className="feature-icon">⌂</span><span><strong>Homes &amp; businesses</strong><small>Built around your use.</small></span></div><div><span className="feature-icon">▦</span><span><strong>Builders welcome</strong><small>Site-ready execution support.</small></span></div><div><span className="feature-icon">✓</span><span><strong>Finishing detail</strong><small>Every trade, coordinated.</small></span></div></div></div>
    <section className="section"><div className="container design-execution-grid"><div className="design-execution-copy"><p className="eyebrow">THE STEADWIN WAY</p><h2>We design it.<br /><em>We execute it.</em></h2><p>STEADWIN GROUP handles the planning, interiors and on-site execution that bring a space together. Whether you are building a new home, upgrading a flat or delivering a commercial site, the work stays connected from first brief to handover.</p><div className="execution-points"><span>01&nbsp; Design direction</span><span>02&nbsp; Scope &amp; quotation</span><span>03&nbsp; On-site execution</span><span>04&nbsp; Final handover</span></div><a className="text-link" href="/about/">How we work <Arrow /></a></div><figure className="design-execution-image"><img src="/assets/design-concepts/02-1000003684.webp" width="1600" height="1200" alt="Design concept for a modern living and dining interior" /><figcaption>Concept reference · Living &amp; dining</figcaption></figure></div></section>
    <section className="section soft-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">FOR EVERY TYPE OF PROJECT</p><h2>One team.<br />Three ways to work.</h2></div><p>Bring a complete project, a builder requirement or a specific interior scope. We match the work to your site, timeline and finish requirements.</p></div><div className="project-types steadwin-project-types"><a className="project-type-card" href="/residential/"><span className="eyebrow">01 / HOME INTERIORS</span><h3>Spaces to live in.</h3><p>Kitchens, wardrobes, living spaces, utilities and all the coordinated finishing work around them.</p><span className="text-link">Explore residential <Arrow /></span></a><a className="project-type-card dark-card" href="/commercial/"><span className="eyebrow">02 / COMMERCIAL</span><h3>Spaces that perform.</h3><p>Offices, shops, showrooms, partitions and execution that supports the way your business works.</p><span className="text-link">Explore commercial <Arrow /></span></a><a className="project-type-card builder-card" href={contactHref("Builder execution", "Builder") }><span className="eyebrow">03 / BUILDERS</span><h3>Spaces ready to deliver.</h3><p>Interior execution, glass, aluminium, railings, skylights and coordinated site work for builder projects.</p><span className="text-link">Discuss a builder scope <Arrow /></span></a></div></div></section>
    <section className="section"><div className="container"><div className="section-heading"><div><p className="eyebrow">OUR EXPERTISE</p><h2>Every trade.<br />Every finishing detail.</h2></div><a className="text-link" href="/services/">View all services <Arrow /></a></div><ServiceCards items={[services[0], services[1], services[5], services[7]]} /></div></section>
    <section className="section concept-preview-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">DESIGN CONCEPTS</p><h2>Ideas for the space<br />you want to create.</h2></div><a className="text-link" href="/gallery/">View all concepts <Arrow /></a></div><div className="concept-preview-grid">{designConcepts.slice(0, 9).map((item, index) => <a className={"concept-preview-card" + (index === 0 ? " concept-preview-large" : "")} href="/gallery/" key={item.image}><img src={"/assets/" + item.image} width="1600" height="1200" alt={item.alt} loading="lazy" /><span><small>{item.subtitle}</small><strong>{item.title}</strong></span></a>)}</div><p className="gallery-note">These are design and execution references shared for inspiration. Completed STEADWIN work is shown separately in the Projects section.</p></div></section>
    <ProjectQuickActions /><CTA />
  </SiteShell>;
}

export function AboutPage() {
  return <SiteShell active="about"><PageIntro label="ABOUT STEADWIN GROUP" current="About" title={<>Interiors for the way<br />you <em>live &amp; work.</em></>} text="Based in Bengaluru, we undertake complete interior projects and individual installation and finishing works for residential and commercial spaces." />
    <section className="section"><div className="container split-section"><ImagePanel src="living.webp" alt="Living room design inspiration with warm wood detailing" caption="Living & dining · Design inspiration" priority /><div className="section-copy"><p className="eyebrow">A CONNECTED APPROACH</p><h2>From the first requirement<br />to the finishing details.</h2><p>A room comes together through many kinds of work. Furniture needs the right electrical points. Surfaces need preparation. Glass, lighting and finishes need to work with the layout.</p><p>STEADWIN GROUP brings these interior requirements into a clear discussion of scope, materials and execution. We work across homes, apartments, villas, offices, shops and showrooms.</p><div className="inline-facts"><div><strong>Residential</strong><span>Homes, apartments &amp; villas</span></div><div><strong>Commercial</strong><span>Offices, shops &amp; showrooms</span></div></div></div></div></section>
    <section className="section dark-section about-principles" aria-labelledby="about-principles-title"><div className="container"><div className="section-heading"><div><p className="eyebrow">WHAT MATTERS IN YOUR PROJECT</p><h2 id="about-principles-title">The right details,<br />discussed from the start.</h2></div><a className="text-link" href="/services/">Explore our expertise <Arrow /></a></div><div className="principles"><article><span>01</span><h3>Your space, your scope</h3><p>Discuss a complete interior or selected works based on your property and requirements.</p></article><article><span>02</span><h3>Materials with a purpose</h3><p>Review the materials, finishes and installation needs for the way the space will be used.</p></article><article><span>03</span><h3>A clear next step</h3><p>Bring site details and references so the quotation and schedule can reflect your project.</p></article></div></div></section>
    <Process /><CTA />
  </SiteShell>;
}

export function ServicesPage() {
  return <SiteShell active="services"><PageIntro label="OUR SERVICES" current="Services" title={<>Complete interiors.<br /><em>Every trade covered.</em></>} text="Explore our interior, installation and finishing services. Choose a complete project or the individual work your home or business needs." />
    <section className="section services-directory"><div className="container"><div className="directory-heading"><span>INTERIOR &amp; RELATED WORKS</span><span>RESIDENTIAL + COMMERCIAL</span></div><ServiceCards /><p className="scope-note">The final scope, specifications, cost and timeline depend on your site and agreed requirements.</p></div></section>
    <section className="section soft-section"><div className="container project-paths"><div><p className="eyebrow">START WITH YOUR SPACE</p><h2>A home or a business?<br />Find your starting point.</h2></div><div><a href="/residential/"><span>Residential interiors<small>Homes, apartments &amp; villas</small></span><Arrow /></a><a href="/commercial/"><span>Commercial interiors<small>Offices, shops &amp; showrooms</small></span><Arrow /></a></div></div></section><CTA />
  </SiteShell>;
}

export function ServicePage({ slug }: { slug: string }) {
  const service = services.find(item => item.slug === slug);
  if (!service) return null;
  const related = services.filter(item => item.slug !== slug).slice(0, 3);
  return <SiteShell active="services"><section className="service-hero"><div className="container"><Breadcrumbs current={service.short} service /><div className="service-hero-grid"><div><p className="eyebrow">{service.number} / {service.category}</p><h1>{service.title}</h1><p>{service.intro}</p><a className="button button-blue" href={contactHref(service.title)}>Enquire about this service <Arrow /></a></div><div className="service-applications"><p className="eyebrow">FOR YOUR SPACE</p>{service.applications.map(item => <span key={item}>{item}</span>)}<a href="/services/" className="text-link">All services <span aria-hidden="true">→</span></a></div></div></div></section>
    <section className="section"><div className="container detail-layout"><div className="detail-main"><p className="eyebrow">THE SCOPE</p><h2>Work that fits<br />your requirements.</h2><p className="lead-copy">{service.description}</p><ul className="scope-list">{service.works.map(work => <li key={work}><span aria-hidden="true">✓</span>{work}</li>)}</ul>{service.image && <ImagePanel src={service.image} alt={service.imageAlt} caption="Concept visual · Design inspiration" />}</div><aside className="enquiry-aside"><p className="eyebrow">PLAN YOUR PROJECT</p><h3>Let’s discuss the details.</h3><p>{service.considerations}</p><a className="button button-dark" href={contactHref(service.title)}>Discuss this service <Arrow /></a><a className="aside-phone" href={"tel:" + company.tel}>{company.phone}</a><p className="aside-note">Residential &amp; commercial<br />Bengaluru, Karnataka</p></aside></div></section>
    <section className="section soft-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">BRING THE WORK TOGETHER</p><h2>Explore related services.</h2></div><a className="text-link" href="/services/">All services <Arrow /></a></div><div className="related-services">{related.map(item => <a href={"/services/" + item.slug + "/"} key={item.slug}><span>{item.number}</span><h3>{item.short}</h3><Arrow /></a>)}</div></div></section>
  </SiteShell>;
}

const residentialSpaces = [
  { title: "Living & dining", text: "TV units, pooja units, panelling, storage and finishes for shared spaces." },
  { title: "Kitchens & utilities", text: "Modular kitchens, countertops, tiles, plumbing and electrical points." },
  { title: "Bedrooms & wardrobes", text: "Fitted storage, wardrobe work, lighting and coordinated finishes." },
  { title: "The complete home", text: "Painting, POP, flooring, glass, railings, networking and related installations." },
];

export function ResidentialPage() {
  return <SiteShell active="residential"><PageIntro label="RESIDENTIAL INTERIORS" current="Residential" title={<>Make room for<br /><em>the way you live.</em></>} text="Complete interior and individual works for apartments, villas and homes. Start with a room, a renovation or your entire home." />
    <section className="section"><div className="container split-section"><div className="section-copy"><p className="eyebrow">YOUR HOME, CONSIDERED</p><h2>Everyday spaces.<br />Thoughtful details.</h2><p>Storage, movement, light and material choices all shape how your home feels. Discuss the rooms you use, the work you need and the finish you have in mind.</p><p>We bring carpentry and interior finishes together with electrical, plumbing and the other installations your home requires.</p><a className="button button-dark" href={contactHref("Complete interior work", "Residential")}>Discuss your home <Arrow /></a></div><ImagePanel src="bedroom.webp" alt="Bedroom and wardrobe design inspiration with walnut storage and natural light" caption="Bedroom & wardrobes · Design inspiration" priority /></div></section>
    <section className="section soft-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">ROOM BY ROOM</p><h2>A place for everything.</h2></div><a className="text-link" href="/gallery/">Explore inspiration <Arrow /></a></div><div className="space-grid">{residentialSpaces.map((item, i) => <article key={item.title}><span className="service-number">0{i + 1}</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></div></section>
    <section className="section"><div className="container"><div className="section-heading"><div><p className="eyebrow">FROM INSTALLATION TO FINISH</p><h2>Services for your home.</h2></div><a className="text-link" href="/services/">All services <Arrow /></a></div><ServiceCards items={[services[0], services[2], services[3], services[6]]} /></div></section><CTA title="Let’s talk about your home." text="Share your location, the rooms to be worked on and your interior requirements." service="Complete interior work" project="Residential" />
  </SiteShell>;
}

export function CommercialPage() {
  return <SiteShell active="commercial"><PageIntro label="COMMERCIAL INTERIORS" current="Commercial" title={<>A space that works.<br /><em>For your business.</em></>} text="Interior execution and related installations for offices, shops, showrooms and commercial spaces in Bengaluru." dark />
    <section className="section"><div className="container commercial-overview"><div className="section-copy"><p className="eyebrow">BUILT AROUND YOUR REQUIREMENTS</p><h2>Connect the layout.<br />Coordinate the work.</h2><p>A business interior brings many requirements together: defined work areas, electrical points, network connections, storage, lighting and the right surfaces.</p><p>Discuss a complete commercial interior or selected works. We review the site and your requirements to establish the scope and sequence.</p><a className="button button-dark" href={contactHref("Complete interior work", "Commercial")}>Discuss your business space <Arrow /></a></div><div className="commercial-spaces"><p className="eyebrow">SPACES WE WORK ON</p><article><span>01</span><div><h3>Offices &amp; workspaces</h3><p>Cabins, meeting areas, partitions, installations and finishes.</p></div></article><article><span>02</span><div><h3>Shops &amp; showrooms</h3><p>Interior execution, surface finishes, glass and related works.</p></div></article><article><span>03</span><div><h3>Commercial renovations</h3><p>Changes and updates to suit the requirements of an existing space.</p></div></article></div></div></section>
    <section className="section soft-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">WORKPLACE ESSENTIALS</p><h2>The installations behind<br />a working space.</h2></div><a className="text-link" href="/services/">View all services <Arrow /></a></div><ServiceCards items={[services[7], services[4], services[1], services[5]]} /></div></section>
    <section className="section"><div className="container briefing-strip"><div><p className="eyebrow">BEFORE WE BEGIN</p><h2>Bring your business<br />requirements into focus.</h2></div><ul className="scope-list"><li><span aria-hidden="true">✓</span>Site location and approximate floor area</li><li><span aria-hidden="true">✓</span>Existing layout or a floor plan</li><li><span aria-hidden="true">✓</span>Workstations, cabins and service requirements</li><li><span aria-hidden="true">✓</span>Preferred finishes and intended schedule</li></ul></div></section><CTA title="Plan your next business space." text="Tell us about your office, shop or showroom and the work you need." service="Complete interior work" project="Commercial" />
  </SiteShell>;
}

export function GalleryPage() {
  return <SiteShell active="gallery"><PageIntro label="DESIGN CONCEPTS" current="Concepts" title={<>Explore the ideas.<br /><em>Plan the real space.</em></>} text="A large collection of interior, builder, glass and execution references to help start the conversation for your property." />
    <section className="section gallery-section concept-gallery-section"><div className="container"><div className="concept-gallery-head"><div><p className="eyebrow">YOUR REFERENCE LIBRARY</p><h2>Interior design.<br />Builder execution.</h2></div><p>Browse the concepts, open any visual in full screen and share the ideas you like with our team on WhatsApp.</p></div><div className="concept-filter" aria-label="Filter concepts"><button type="button" className="is-active" data-concept-filter="all">All concepts <span>{designConcepts.length}</span></button><button type="button" data-concept-filter="interiors">Interior design</button><button type="button" data-concept-filter="execution">Glass + builder</button></div><div className="concept-gallery-grid">{designConcepts.map((item, i) => <button className={"concept-gallery-card" + (i === 0 ? " is-featured" : "")} key={item.image} data-gallery={i} data-concept-category={item.category} type="button" aria-label={"Open " + item.title + " reference"}><span className="concept-gallery-image"><img src={"/assets/" + item.image} alt={item.alt} width="1600" height="1200" loading={i < 8 ? "eager" : "lazy"} fetchPriority={i < 2 ? "high" : undefined} /><span className="image-open" aria-hidden="true">↗</span></span><span className="concept-gallery-caption"><small>{item.subtitle}</small><strong>{item.title}</strong><em>Reference {String(i + 1).padStart(3, "0")}</em></span></button>)}</div><p className="gallery-note">These are 3D design and execution references supplied for inspiration. They are not photographs of completed STEADWIN projects. Completed project photography stays separate in <a href="/projects/">Projects <Arrow /></a>.</p></div></section>
    <CTA title="Seen an idea you like?" text="Share the reference number, your location and the work you need. We will take the conversation forward on WhatsApp." project="Residential" />
    <dialog className="lightbox" id="gallery-dialog" aria-labelledby="lightbox-caption"><button className="lightbox-close" type="button" aria-label="Close gallery">×</button><img id="lightbox-image" src={"/assets/" + designConcepts[0].image} alt="" /><div className="lightbox-bottom"><p id="lightbox-caption">Design concept</p><div className="lightbox-controls"><button type="button" id="gallery-prev" aria-label="Previous image">←</button><span id="gallery-count" aria-live="polite"></span><button type="button" id="gallery-next" aria-label="Next image">→</button></div></div></dialog>
  </SiteShell>;
}

export function ContactPage() {
  return <SiteShell active="contact"><PageIntro label="START YOUR PROJECT" current="Contact" title={<>Your next space starts<br /><em>with a clear brief.</em></>} text="Home, office, commercial site or builder requirement — tell us what you are planning and we will help define the right next step." />
    <section className="section contact-section"><div className="container contact-grid"><div className="contact-copy"><p className="eyebrow">LET’S CONNECT</p><h2>We’re here<br />in Bengaluru.</h2><div className="contact-details"><a href={"tel:" + company.tel}><small>OFFICE NUMBER</small><span>{company.phone} <Arrow /></span></a><a href={"mailto:" + company.email}><small>EMAIL</small><span>{company.email} <Arrow /></span></a><div><small>OFFICE ADDRESS</small><address>{company.address}</address><a className="text-link directions" href={"https://www.google.com/maps/search/?api=1&query=" + encodeURIComponent(company.address)} target="_blank" rel="noopener noreferrer">Get directions <Arrow /></a></div></div><div className="contact-projects"><span>Residential</span><span>Commercial</span><span>Individual works</span></div></div>
    <form className="enquiry-form steadwin-enquiry-form" id="enquiry" action="https://wa.me/918792695400" method="get" target="_blank" rel="noopener noreferrer"><p className="eyebrow">PROJECT ENQUIRY</p><h3>Tell us about your project</h3><p>Share a few details. We will prepare the conversation around your actual requirement.</p><div className="form-grid"><label htmlFor="name">Your name<input id="name" type="text" placeholder="Full name" autoComplete="name" required maxLength={100} /></label><label htmlFor="mobile">Mobile number<input id="mobile" type="tel" placeholder="+91 mobile number" autoComplete="tel" required inputMode="tel" maxLength={20} /></label><label htmlFor="email">Email address<input id="email" type="email" placeholder="name@email.com" autoComplete="email" maxLength={120} /></label><label htmlFor="city">City / project location<input id="city" type="text" placeholder="Area or city" autoComplete="address-level2" required maxLength={150} /></label></div><div className="form-grid"><label htmlFor="project-type">Project type<select id="project-type" required defaultValue=""><option value="" disabled>Select project type</option><option>Residential interior</option><option>Commercial interior</option><option>Builder execution</option><option>Renovation / individual work</option></select></label><label htmlFor="service">Service required<select id="service">{services.map(item => <option key={item.slug}>{item.title}</option>)}</select></label></div><label htmlFor="message">Project brief<textarea id="message" rows={5} placeholder="Share your area, preferred style, rooms or work scope, and expected timeline…" required maxLength={2000}></textarea></label><input id="whatsapp-text" name="text" type="hidden" defaultValue="Hello STEADWIN GROUP, I would like to discuss a project." /><p className="form-note">This securely opens WhatsApp with your enquiry details. You can add drawings, floor plans or site photos in the chat.</p><button className="button button-dark" type="submit">Send project enquiry <Arrow /></button><noscript><p className="form-note">Enable JavaScript to include your project details automatically, or contact us by phone or email.</p></noscript></form></div></section>
    <section className="section"><div className="container faq"><div><p className="eyebrow">BEFORE WE BEGIN</p><h2>A little clarity<br />goes a long way.</h2></div><div><details><summary>Do you take up complete and individual works?<span aria-hidden="true">+</span></summary><p>Yes. We undertake complete residential and commercial interiors as well as individual installation and finishing works. Share your requirements to discuss the scope.</p></details><details><summary>How are the cost and timeline decided?<span aria-hidden="true">+</span></summary><p>Site measurements, materials, the agreed design and installation requirements determine the quotation and schedule. These are discussed for your project before work begins.</p></details><details><summary>Can I book a free site visit?<span aria-hidden="true">+</span></summary><p>Yes. Share the project location, approximate area and the work you need through the enquiry form or WhatsApp. The team will discuss the suitable next step with you.</p></details><details><summary>Which Bengaluru areas do you serve?<span aria-hidden="true">+</span></summary><p>We are based in JP Nagar and discuss residential and commercial interior requirements across Bengaluru, subject to the project scope and location.</p></details><details><summary>What should I share in my first enquiry?<span aria-hidden="true">+</span></summary><p>Share your project location, whether it is residential or commercial, and the services you need. Floor plans, site photos and reference images can be shared in your WhatsApp conversation.</p></details></div></div></section>
    <ContactGrowth />
  </SiteShell>;
}
