import { Arrow, Breadcrumbs, CTA, ImagePanel, PageIntro, Process, ServiceCards, SiteShell } from "./site";
import { ContactGrowth, ProjectQuickActions } from "./growth";
import { company, contactHref, gallery, services } from "@/data/site-data";

export function HomePage() {
  return <SiteShell active="home">
    <section className="hero aluvex-hero"><div className="hero-image"><img src="/assets/living.webp" width="1672" height="941" alt="Design inspiration: a contemporary living and dining room with walnut finishes" fetchPriority="high" /></div><div className="hero-shade"></div><div className="container hero-content"><p className="eyebrow">SPACES WITH A BRIGHTER TOMORROW <span className="hero-rule"></span></p><h1>Complete Interior<br />Work for <span>Modern Spaces</span></h1><h2>Beautiful. Functional. Finished.</h2><p className="hero-description">From complete home interiors to commercial spaces, STEADWIN GROUP brings every trade and finishing detail together with clear project coordination.</p><div className="hero-actions"><a className="button button-blue" href={contactHref()}>Get Free Consultation <Arrow /></a><a className="button button-outline" href="https://wa.me/918792695400" target="_blank" rel="noopener noreferrer"><span className="whatsapp-dot">●</span> WhatsApp Us</a></div></div><div className="hero-badge">MODERN<br />SPACES<br />STRONGER<br />LIVING</div></section>
    <div className="feature-strip"><div className="container feature-grid"><div><span className="feature-icon">✦</span><span><strong>Complete Interiors</strong><small>Every detail, coordinated.</small></span></div><div><span className="feature-icon">◇</span><span><strong>Residential &amp; Commercial</strong><small>For every kind of space.</small></span></div><div><span className="feature-icon">⌁</span><span><strong>Professional Work</strong><small>Planned around your site.</small></span></div><div><span className="feature-icon">✓</span><span><strong>Quality Finishes</strong><small>Made for everyday use.</small></span></div></div></div>
    <section className="section"><div className="container"><div className="section-heading"><div><p className="eyebrow">DESIGNED AROUND YOUR SPACE</p><h2>One team of trades.<br />Two worlds of possibilities.</h2></div><p>Complete projects and individual interior works for homes, offices, shops and showrooms.</p></div><div className="project-types"><a className="project-type-card" href="/residential/"><span className="eyebrow">01 / RESIDENTIAL</span><h3>Spaces to call home.</h3><p>Kitchens, wardrobes, living spaces and the installations that bring them together.</p><span className="text-link">Residential interiors <Arrow /></span></a><a className="project-type-card dark-card" href="/commercial/"><span className="eyebrow">02 / COMMERCIAL</span><h3>Spaces that work for you.</h3><p>Interiors, partitions and related works for your business environment.</p><span className="text-link">Commercial interiors <Arrow /></span></a></div></div></section>
    <section className="section soft-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">OUR EXPERTISE</p><h2>Every trade.<br />Every finishing detail.</h2></div><a className="text-link" href="/services/">View all services <Arrow /></a></div><ServiceCards items={[services[0], services[1], services[5], services[7]]} /></div></section>
    <section className="section"><div className="container split-section"><ImagePanel src="kitchen.webp" alt="Kitchen design inspiration with graphite cabinets and light stone finishes" caption="Modular kitchen · Design inspiration" /><div className="section-copy"><p className="eyebrow">THE STEADWIN APPROACH</p><h2>Interior work,<br />brought together.</h2><p>We undertake complete interior and related works for residential and commercial spaces in Bengaluru. Start with a whole project or the individual services your space needs.</p><p>From electrical and plumbing to paint, POP, granite, tiles, networking, CCTV, glass and aluminium, discuss the work as one connected scope.</p><a className="text-link" href="/about/">Get to know STEADWIN <Arrow /></a></div></div></section>
    <ProjectQuickActions /><CTA />
  </SiteShell>;
}

export function AboutPage() {
  return <SiteShell active="about"><PageIntro label="ABOUT STEADWIN GROUP" current="About" title={<>Interiors for the way<br />you <em>live &amp; work.</em></>} text="Based in Bengaluru, we undertake complete interior projects and individual installation and finishing works for residential and commercial spaces." />
    <section className="section"><div className="container split-section"><ImagePanel src="living.webp" alt="Living room design inspiration with warm wood detailing" caption="Living & dining · Design inspiration" priority /><div className="section-copy"><p className="eyebrow">A CONNECTED APPROACH</p><h2>From the first requirement<br />to the finishing details.</h2><p>A room comes together through many kinds of work. Furniture needs the right electrical points. Surfaces need preparation. Glass, lighting and finishes need to work with the layout.</p><p>STEADWIN GROUP brings these interior requirements into a clear discussion of scope, materials and execution. We work across homes, apartments, villas, offices, shops and showrooms.</p><div className="inline-facts"><div><strong>Residential</strong><span>Homes, apartments &amp; villas</span></div><div><strong>Commercial</strong><span>Offices, shops &amp; showrooms</span></div></div></div></div></section>
    <section className="section dark-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">WHAT MATTERS IN YOUR PROJECT</p><h2>The right details,<br />discussed from the start.</h2></div><a className="text-link" href="/services/">Explore our expertise <Arrow /></a></div><div className="principles"><article><span>01</span><h3>Your space, your scope</h3><p>Discuss a complete interior or selected works based on your property and requirements.</p></article><article><span>02</span><h3>Materials with a purpose</h3><p>Review the materials, finishes and installation needs for the way the space will be used.</p></article><article><span>03</span><h3>A clear next step</h3><p>Bring site details and references so the quotation and schedule can reflect your project.</p></article></div></div></section>
    <Process /><CTA />
  </SiteShell>;
}

export function ServicesPage() {
  return <SiteShell active="services"><PageIntro label="OUR SERVICES" current="Services" title={<>Complete interiors.<br /><em>Every trade covered.</em></>} text="Explore our interior, installation and finishing services. Choose a complete project or the individual work your home or business needs." />
    <section className="section services-directory"><div className="container"><div className="directory-heading"><span>INTERIOR &amp; RELATED WORKS</span><span>RESIDENTIAL + COMMERCIAL</span></div><ServiceCards /><p className="scope-note">The final scope, specifications, cost and timeline depend on your site and agreed requirements.</p></div></section>
    <section className="section soft-section"><div className="container project-paths"><div><p className="eyebrow">START WITH YOUR SPACE</p><h2>A home or a business?<br />Find your starting point.</h2></div><div><a href="/residential/"><span>Residential interiors<small>Homes, apartments &amp; villas</small></span><Arrow /></a><a href="/commercial/"><span>Commercial interiors<small>Offices, shops &amp; showrooms</small></span><Arrow /></a></div></div></section><CTA />
  </SiteShell>;
}

export function ServicePage({ slug }: { slug: string }) {
  const service = services.find(item => item.slug === slug);
  if (!service) return null;
  const related = services.filter(item => item.slug !== slug).slice(0, 3);
  return <SiteShell active="services"><section className="service-hero"><div className="container"><Breadcrumbs current={service.short} service /><div className="service-hero-grid"><div><p className="eyebrow">{service.number} / {service.category}</p><h1>{service.title}</h1><p>{service.intro}</p><a className="button button-blue" href={contactHref(service.title)}>Enquire about this service <Arrow /></a></div><div className="service-applications"><p className="eyebrow">FOR YOUR SPACE</p>{service.applications.map(item => <span key={item}>{item}</span>)}<a href="/services/" className="text-link">All services <span aria-hidden="true">→</span></a></div></div></div></section>
    <section className="section"><div className="container detail-layout"><div className="detail-main"><p className="eyebrow">THE SCOPE</p><h2>Work that fits<br />your requirements.</h2><p className="lead-copy">{service.description}</p><ul className="scope-list">{service.works.map(work => <li key={work}><span aria-hidden="true">✓</span>{work}</li>)}</ul>{service.image && <ImagePanel src={service.image} alt={service.imageAlt} caption="Concept visual · Design inspiration" />}</div><aside className="enquiry-aside"><p className="eyebrow">PLAN YOUR PROJECT</p><h3>Let’s discuss the details.</h3><p>{service.considerations}</p><a className="button button-dark" href={contactHref(service.title)}>Discuss this service <Arrow /></a><a className="aside-phone" href={"tel:" + company.tel}>{company.phone}</a><p className="aside-note">Residential &amp; commercial<br />Bengaluru, Karnataka</p></aside></div></section>
    <section className="section soft-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">BRING THE WORK TOGETHER</p><h2>Explore related services.</h2></div><a className="text-link" href="/services/">All services <Arrow /></a></div><div className="related-services">{related.map(item => <a href={"/services/" + item.slug + "/"} key={item.slug}><span>{item.number}</span><h3>{item.short}</h3><Arrow /></a>)}</div></div></section>
  </SiteShell>;
}

const residentialSpaces = [
  { title: "Living & dining", text: "TV units, pooja units, panelling, storage and finishes for shared spaces." },
  { title: "Kitchens & utilities", text: "Modular kitchens, countertops, tiles, plumbing and electrical points." },
  { title: "Bedrooms & wardrobes", text: "Fitted storage, wardrobe work, lighting and coordinated finishes." },
  { title: "The complete home", text: "Painting, POP, flooring, glass, railings, networking and related installations." },
];

export function ResidentialPage() {
  return <SiteShell active="residential"><PageIntro label="RESIDENTIAL INTERIORS" current="Residential" title={<>Make room for<br /><em>the way you live.</em></>} text="Complete interior and individual works for apartments, villas and homes. Start with a room, a renovation or your entire home." />
    <section className="section"><div className="container split-section"><div className="section-copy"><p className="eyebrow">YOUR HOME, CONSIDERED</p><h2>Everyday spaces.<br />Thoughtful details.</h2><p>Storage, movement, light and material choices all shape how your home feels. Discuss the rooms you use, the work you need and the finish you have in mind.</p><p>We bring carpentry and interior finishes together with electrical, plumbing and the other installations your home requires.</p><a className="button button-dark" href={contactHref("Complete interior work", "Residential")}>Discuss your home <Arrow /></a></div><ImagePanel src="bedroom.webp" alt="Bedroom and wardrobe design inspiration with walnut storage and natural light" caption="Bedroom & wardrobes · Design inspiration" priority /></div></section>
    <section className="section soft-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">ROOM BY ROOM</p><h2>A place for everything.</h2></div><a className="text-link" href="/gallery/">Explore inspiration <Arrow /></a></div><div className="space-grid">{residentialSpaces.map((item, i) => <article key={item.title}><span className="service-number">0{i + 1}</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></div></section>
    <section className="section"><div className="container"><div className="section-heading"><div><p className="eyebrow">FROM INSTALLATION TO FINISH</p><h2>Services for your home.</h2></div><a className="text-link" href="/services/">All services <Arrow /></a></div><ServiceCards items={[services[0], services[2], services[3], services[6]]} /></div></section><CTA title="Let’s talk about your home." text="Share your location, the rooms to be worked on and your interior requirements." service="Complete interior work" project="Residential" />
  </SiteShell>;
}

export function CommercialPage() {
  return <SiteShell active="commercial"><PageIntro label="COMMERCIAL INTERIORS" current="Commercial" title={<>A space that works.<br /><em>For your business.</em></>} text="Interior execution and related installations for offices, shops, showrooms and commercial spaces in Bengaluru." dark />
    <section className="section"><div className="container commercial-overview"><div className="section-copy"><p className="eyebrow">BUILT AROUND YOUR REQUIREMENTS</p><h2>Connect the layout.<br />Coordinate the work.</h2><p>A business interior brings many requirements together: defined work areas, electrical points, network connections, storage, lighting and the right surfaces.</p><p>Discuss a complete commercial interior or selected works. We review the site and your requirements to establish the scope and sequence.</p><a className="button button-dark" href={contactHref("Complete interior work", "Commercial")}>Discuss your business space <Arrow /></a></div><div className="commercial-spaces"><p className="eyebrow">SPACES WE WORK ON</p><article><span>01</span><div><h3>Offices &amp; workspaces</h3><p>Cabins, meeting areas, partitions, installations and finishes.</p></div></article><article><span>02</span><div><h3>Shops &amp; showrooms</h3><p>Interior execution, surface finishes, glass and related works.</p></div></article><article><span>03</span><div><h3>Commercial renovations</h3><p>Changes and updates to suit the requirements of an existing space.</p></div></article></div></div></section>
    <section className="section soft-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">WORKPLACE ESSENTIALS</p><h2>The installations behind<br />a working space.</h2></div><a className="text-link" href="/services/">View all services <Arrow /></a></div><ServiceCards items={[services[7], services[4], services[1], services[5]]} /></div></section>
    <section className="section"><div className="container briefing-strip"><div><p className="eyebrow">BEFORE WE BEGIN</p><h2>Bring your business<br />requirements into focus.</h2></div><ul className="scope-list"><li><span aria-hidden="true">✓</span>Site location and approximate floor area</li><li><span aria-hidden="true">✓</span>Existing layout or a floor plan</li><li><span aria-hidden="true">✓</span>Workstations, cabins and service requirements</li><li><span aria-hidden="true">✓</span>Preferred finishes and intended schedule</li></ul></div></section><CTA title="Plan your next business space." text="Tell us about your office, shop or showroom and the work you need." service="Complete interior work" project="Commercial" />
  </SiteShell>;
}

export function GalleryPage() {
  return <SiteShell active="gallery"><PageIntro label="DESIGN INSPIRATION" current="Gallery" title={<>Imagine<br /><em>the possibilities.</em></>} text="Explore residential interior concepts for living, cooking and unwinding. Use these ideas as a starting point for your own space." />
    <section className="section gallery-section"><div className="container"><div className="gallery-grid">{gallery.map((item, i) => <button className={"gallery-card" + (i === 0 ? " gallery-featured" : "")} key={item.image} data-gallery={i} type="button" aria-label={"View " + item.title.toLowerCase() + " inspiration"}><span className="gallery-image"><img src={"/assets/" + item.image} alt={item.alt} width={item.width} height={item.height} loading={i === 0 ? "eager" : "lazy"} fetchPriority={i === 0 ? "high" : undefined} /><span className="image-open" aria-hidden="true">↗</span></span><span className="gallery-caption"><span><small>{item.subtitle}</small><strong>{item.title}</strong></span><span>0{i + 1}</span></span></button>)}</div><p className="gallery-note">These are concept visuals for design inspiration, not photographs of completed STEADWIN projects. Your design, materials and scope are discussed for your property.</p></div></section>
    <CTA title="Seen an idea you like?" text="Tell us what you would like to bring into your home. Share references in your WhatsApp conversation." project="Residential" />
    <dialog className="lightbox" id="gallery-dialog" aria-labelledby="lightbox-caption"><button className="lightbox-close" type="button" aria-label="Close gallery">×</button><img id="lightbox-image" src="/assets/living.webp" alt="" /><div className="lightbox-bottom"><p id="lightbox-caption">Design inspiration</p><div className="lightbox-controls"><button type="button" id="gallery-prev" aria-label="Previous image">←</button><span id="gallery-count" aria-live="polite"></span><button type="button" id="gallery-next" aria-label="Next image">→</button></div></div></dialog>
  </SiteShell>;
}

export function ContactPage() {
  return <SiteShell active="contact"><PageIntro label="CONTACT STEADWIN GROUP" current="Contact" title={<>Your next space starts<br /><em>with a conversation.</em></>} text="A home, an office or a complete commercial interior. Tell us about your space and the work you need." />
    <section className="section contact-section"><div className="container contact-grid"><div className="contact-copy"><p className="eyebrow">LET’S CONNECT</p><h2>We’re here<br />in Bengaluru.</h2><div className="contact-details"><a href={"tel:" + company.tel}><small>OFFICE NUMBER</small><span>{company.phone} <Arrow /></span></a><a href={"mailto:" + company.email}><small>EMAIL</small><span>{company.email} <Arrow /></span></a><div><small>OFFICE ADDRESS</small><address>{company.address}</address><a className="text-link directions" href={"https://www.google.com/maps/search/?api=1&query=" + encodeURIComponent(company.address)} target="_blank" rel="noopener noreferrer">Get directions <Arrow /></a></div></div><div className="contact-projects"><span>Residential</span><span>Commercial</span><span>Individual works</span></div></div>
    <form className="enquiry-form" id="enquiry" action="https://wa.me/918792695400" method="get" target="_blank" rel="noopener noreferrer"><p className="eyebrow">PROJECT ENQUIRY</p><h3>Tell us about your project</h3><p>A few details to get the conversation started.</p><div className="form-grid"><label htmlFor="name">Your name<input id="name" type="text" placeholder="Full name" autoComplete="name" required maxLength={100} /></label><label htmlFor="location">Project location<input id="location" type="text" placeholder="Area or city" autoComplete="address-level2" maxLength={150} /></label></div><label htmlFor="project-type">Project type<select id="project-type" required defaultValue=""><option value="" disabled>Select residential or commercial</option><option>Residential</option><option>Commercial</option></select></label><label htmlFor="service">What can we help with?<select id="service">{services.map(item => <option key={item.slug}>{item.title}</option>)}</select></label><label htmlFor="message">About your space<textarea id="message" rows={4} placeholder="Tell us the area, services and work you need…" required maxLength={2000}></textarea></label><input id="whatsapp-text" name="text" type="hidden" defaultValue="Hello STEADWIN GROUP, I would like to discuss an interior project." /><p className="form-note">This opens WhatsApp with your enquiry. Review the details and tap Send to contact us.</p><button className="button button-dark" type="submit">Continue on WhatsApp <Arrow /></button><noscript><p className="form-note">Enable JavaScript to include your project details automatically, or contact us by phone or email.</p></noscript></form></div></section>
    <section className="section"><div className="container faq"><div><p className="eyebrow">BEFORE WE BEGIN</p><h2>A little clarity<br />goes a long way.</h2></div><div><details><summary>Do you take up complete and individual works?<span aria-hidden="true">+</span></summary><p>Yes. We undertake complete residential and commercial interiors as well as individual installation and finishing works. Share your requirements to discuss the scope.</p></details><details><summary>How are the cost and timeline decided?<span aria-hidden="true">+</span></summary><p>Site measurements, materials, the agreed design and installation requirements determine the quotation and schedule. These are discussed for your project before work begins.</p></details><details><summary>Can I book a free site visit?<span aria-hidden="true">+</span></summary><p>Yes. Share the project location, approximate area and the work you need through the enquiry form or WhatsApp. The team will discuss the suitable next step with you.</p></details><details><summary>Which Bengaluru areas do you serve?<span aria-hidden="true">+</span></summary><p>We are based in JP Nagar and discuss residential and commercial interior requirements across Bengaluru, subject to the project scope and location.</p></details><details><summary>What should I share in my first enquiry?<span aria-hidden="true">+</span></summary><p>Share your project location, whether it is residential or commercial, and the services you need. Floor plans, site photos and reference images can be shared in your WhatsApp conversation.</p></details></div></div></section>
    <ContactGrowth />
  </SiteShell>;
}
